#: import environ os.environ

<RootWidget>:
    text: 'THE BACKGROUND'
    font_size: 150
    Image:
        source: f'{environ["PHYSICS_ROOT"]}/images/colours.png'
        allow_stretch: True
        keep_ratio: False
    Image:
        source: '{environ["PHYSICS_ROOT"]}/images/colours2.png'
        allow_stretch: True
        keep_ratio: False
    Image:
        source: '{environ["PHYSICS_ROOT"]}/images/colours.png'
        allow_stretch: True
        keep_ratio: False